name: Docker


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: codex-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: docker/Dockerfile
      dockerhub_repo: codexstorage/test
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
      amd64_builder: ubuntu-24.04
      build_args: |
        VITE_CODEX_API_URL=${VITE_CODEX_API_URL}
        VITE_GEO_IP_URL="Plain text"
    secrets: inherit
